---
# Per environment values which override defaults in hmpps-prisoner-finance-sync-ui/values.yaml

generic-service:
  ingress:
    host: prisoner-finance-sync-ui.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://prisoner-finance-sync-ui.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api.prison.service.justice.gov.uk"
    PRISONER_FINANCE_SYNC_API_URL: 'https://prisoner-finance-sync-api.hmpps.service.justice.gov.uk'
    AUDIT_ENABLED: "false"

generic-prometheus-alerts:
  alertSeverity: hmpps-prisoner-finance-alerts
